language: go

go:
  - "1.11"

default:  
  - go build $$(go list ./... | grep -v /vendor/)

before_script:
  - go fmt ./...
  - go vet $(go list ./...)
  - set TASKMASTER_OAUTH_CLIENT_SECRET 0xdeadbeef
  
script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
 - bash <(curl -s https://codecov.io/bash)